### ISSUE TITLE
GET de l'api

### ISSUE THREAD

**Issue by LoicJu** [HE-Arc/qlf#6]
User

    Get info (email, pseudo, PP)
    Get friends list
    Get friends research results

Game

    Get current live games
    Get history games
    Get live game update (or push from server ?)

Market

    Get owned ? Or local ?
    Get not owned list (with ID parameter to store last displayed item --> infinite scroll)
    Get research results
    Get game detailed info
    Get updates

Notification

    Get notifications

**Comment by ourfbht** [comment]
Suppression de l'issue (closing), cette dernière n'étant pas assez atomique.
